#!/usr/bin/env bash

sudo apt-get update -y

# A script that installs nginx server on an ubuntu linux distro.
sudo apt-get install nginx -y

# The installed server listens to port 80 (HTTP) for connection
echo 'Hello World!' > /var/www/html/index.html

# And serves a default page index.html on the HTTP  GET request.
service nginx restart
