#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend mzwandile.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 114926-web-01 52.91.121.74:80
        server 114926-web-02 18.204.3.71:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
